# Generated by Django 3.0.8 on 2021-12-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('grado_escolaridad', models.CharField(max_length=15)),
                ('peso_corporal', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Encuestas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Intereses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intereses_personales', models.CharField(max_length=100)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Intereses',
                'ordering': ['intereses_personales'],
            },
        ),
    ]
