# Generated by Django 3.0.8 on 2021-12-12 05:41

from django.db import migrations, models
import encuesta.models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='edad',
            field=models.PositiveIntegerField(validators=[encuesta.models.validar_edad]),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='peso_corporal',
            field=models.FloatField(validators=[encuesta.models.validar_peso]),
        ),
    ]
