# Generated by Django 3.0.8 on 2021-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20211212_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(help_text='Ya existe un usuario con este nombre', max_length=25, unique=True),
        ),
    ]
