# Generated by Django 3.0.8 on 2021-12-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20211212_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='grado_escolaridad',
            field=models.CharField(choices=[('BACHILLER', 'BACHILLER'), ('LICENCIADO', 'LICENCIADO'), ('MASTER', 'MASTER'), ('DOCTOR', 'DOCTOR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=10),
        ),
    ]
